#!/bin/bash

# LEAP Monitoring - Production Environment Setup
# This file documents all environment variables needed for production

echo "🔧 LEAP Monitoring Platform - Production Setup"
echo "=============================================="
echo ""
echo "Environment Variables Required:"
echo ""

# Frontend Environment Variables
echo "📍 FRONTEND (Next.js Dashboard)"
echo "================================"
echo ""
echo "Required:"
echo "  NEXT_PUBLIC_API_BASE_URL"
echo "    Description: Backend API endpoint"
echo "    Example: https://leap-api.com/api/v1"
echo "    Purpose: All API calls route through this URL"
echo ""
echo "Optional:"
echo "  NODE_ENV=production"
echo "    Description: Node environment"
echo "  NEXT_TELEMETRY_DISABLED=1"
echo "    Description: Disable Vercel telemetry"
echo ""

# Backend Environment Variables
echo "📍 BACKEND (Central Collector - Spring Boot)"
echo "=============================================="
echo ""
echo "Required:"
echo "  SPRING_DATA_MONGODB_URI"
echo "    Description: MongoDB connection string"
echo "    Example: mongodb://mongo:27017/logs_db"
echo ""
echo "  SPRING_DATA_MONGODB_DATABASE"
echo "    Description: Database name"
echo "    Example: logs_db"
echo ""
echo "Optional:"
echo "  JAVA_OPTS"
echo "    Description: JVM memory settings"
echo "    Example: -Xms512m -Xmx1024m -XX:+UseG1GC"
echo ""
echo "  SERVER_PORT"
echo "    Description: Server port"
echo "    Example: 8080"
echo ""

# Database Environment Variables
echo "📍 DATABASE (MongoDB)"
echo "===================="
echo ""
echo "  MONGO_INITDB_DATABASE"
echo "    Description: Initial database name"
echo "    Example: logs_db"
echo ""

# Deployment Steps
echo ""
echo "📋 Step-by-Step Deployment"
echo "=========================="
echo ""
echo "1. FRONTEND DEPLOYMENT (Vercel)"
echo "   a. Push code to GitHub"
echo "   b. Connect repo to Vercel dashboard"
echo "   c. Set environment variable:"
echo "      NEXT_PUBLIC_API_BASE_URL = https://your-backend-url/api/v1"
echo "   d. Deploy (automatic on push)"
echo "   e. Get frontend URL: https://your-app.vercel.app"
echo ""

echo "2. BACKEND DEPLOYMENT (Docker Compose or Kubernetes)"
echo "   a. Ensure MongoDB is running"
echo "   b. Build Central Collector:"
echo "      cd central-collector && gradle build"
echo "   c. Start all services:"
echo "      docker-compose up -d"
echo "   d. Verify health:"
echo "      curl http://localhost:8080/api/v1/health"
echo ""

echo "3. CONNECT FRONTEND TO BACKEND"
echo "   a. Update NEXT_PUBLIC_API_BASE_URL in Vercel"
echo "   b. Verify dashboard loads"
echo "   c. Test login with demo@leapmonitoring.com"
echo ""

echo "4. LOAD TEST WITH 60 USERS"
echo "   a. Use Apache JMeter or k6"
echo "   b. Simulate 60 concurrent users"
echo "   c. Monitor response times (target: <500ms)"
echo "   d. Check error rate (target: <1%)"
echo ""

# Production Checklist
echo ""
echo "✅ Production Checklist"
echo "======================"
echo ""
echo "Security:"
echo "  [ ] HTTPS enabled on both frontend and backend"
echo "  [ ] CORS properly configured"
echo "  [ ] JWT secret key configured (not committed to git)"
echo "  [ ] Environment variables not exposed"
echo "  [ ] Database requires authentication"
echo ""

echo "Performance:"
echo "  [ ] Backend memory: 1-1.5 GB"
echo "  [ ] Database memory: 1 GB"
echo "  [ ] Auto-scaling configured (min: 3, max: 10)"
echo "  [ ] CDN enabled for static assets (Vercel provides)"
echo ""

echo "Monitoring:"
echo "  [ ] Error logging configured"
echo "  [ ] Performance metrics enabled"
echo "  [ ] Alerts set up for errors > 1%"
echo "  [ ] Database backups scheduled"
echo ""

echo "Documentation:"
echo "  [ ] API documentation accessible"
echo "  [ ] GitHub README updated"
echo "  [ ] Deployment guide created"
echo "  [ ] Runbook for operations"
echo ""

# Vercel-Specific Setup
echo ""
echo "🚀 Vercel-Specific Configuration"
echo "================================"
echo ""
echo "Steps:"
echo "1. Create account at https://vercel.com"
echo "2. Click 'New Project'"
echo "3. Import GitHub repository"
echo "4. In project settings, add Environment Variable:"
echo ""
echo "   Name: NEXT_PUBLIC_API_BASE_URL"
echo "   Value: https://your-backend-url/api/v1"
echo "   Environments: Production, Preview, Development"
echo ""
echo "5. Click Deploy"
echo ""
echo "Your app will be live at:"
echo "   https://your-project-name.vercel.app"
echo ""

# AWS Elastic Beanstalk Alternative
echo ""
echo "🏗️  AWS Elastic Beanstalk Alternative"
echo "===================================="
echo ""
echo "If using AWS instead of Vercel:"
echo ""
echo "1. Install EB CLI:"
echo "   pip install awsebcli"
echo ""
echo "2. Initialize:"
echo "   eb init -p node.js-20 leap-dashboard"
echo ""
echo "3. Create environment:"
echo "   eb create leap-dashboard-env"
echo ""
echo "4. Set environment variables:"
echo "   eb setenv NEXT_PUBLIC_API_BASE_URL=https://your-api.com/api/v1"
echo ""
echo "5. Deploy:"
echo "   eb deploy"
echo ""

# Google Cloud Run Alternative
echo ""
echo "☁️  Google Cloud Run Alternative"
echo "================================"
echo ""
echo "If using Google Cloud:"
echo ""
echo "1. Build and push Docker image:"
echo "   docker build -t gcr.io/your-project/leap-dashboard ."
echo "   docker push gcr.io/your-project/leap-dashboard"
echo ""
echo "2. Deploy to Cloud Run:"
echo "   gcloud run deploy leap-dashboard \\"
echo "     --image gcr.io/your-project/leap-dashboard \\"
echo "     --platform managed \\"
echo "     --set-env-vars NEXT_PUBLIC_API_BASE_URL=https://your-api.com/api/v1"
echo ""

# Testing
echo ""
echo "🧪 Testing Before Going Live"
echo "============================="
echo ""
echo "1. Functional Tests:"
echo "   [ ] Login page loads"
echo "   [ ] Can login with demo@leapmonitoring.com / demo123"
echo "   [ ] Dashboard displays metrics"
echo "   [ ] Filters work"
echo "   [ ] Incident resolution works"
echo ""

echo "2. Performance Tests:"
echo "   [ ] Page load time < 3s"
echo "   [ ] API response time < 500ms"
echo "   [ ] Handles 60+ concurrent users"
echo ""

echo "3. Security Tests:"
echo "   [ ] XSS protection works"
echo "   [ ] CSRF tokens in place"
echo "   [ ] Session timeout works"
echo ""

# Monitoring Setup
echo ""
echo "📊 Monitoring Setup"
echo "==================="
echo ""
echo "Recommended Tools:"
echo "  1. Vercel Analytics (built-in if using Vercel)"
echo "  2. DataDog for APM"
echo "  3. New Relic for full-stack"
echo "  4. CloudWatch (if using AWS)"
echo ""

echo "Key Metrics to Monitor:"
echo "  - Response time (p50, p95, p99)"
echo "  - Error rate (%)"
echo "  - Concurrent users"
echo "  - Database query time"
echo "  - Memory usage"
echo "  - CPU usage"
echo ""

# Troubleshooting
echo ""
echo "🔧 Common Issues & Solutions"
echo "============================="
echo ""
echo "Issue: Frontend can't reach backend"
echo "Solution: Check NEXT_PUBLIC_API_BASE_URL is set correctly"
echo ""
echo "Issue: Login page shows infinite loading"
echo "Solution: Check browser console for CORS errors"
echo ""
echo "Issue: Dashboard slow for 60 users"
echo "Solution: Increase backend memory or add more instances"
echo ""

echo ""
echo "✅ Ready for production!"
echo ""
