#!/bin/bash

# ============================================
# LEAP Monitoring Platform - Quick Commands
# ============================================

echo "🚀 LEAP Monitoring Platform - Command Reference"
echo "=============================================="
echo ""
echo "✅ All services are currently running!"
echo ""
echo "📍 Access URLs:"
echo "   • Dashboard: http://localhost:3000"
echo "   • Collector: http://localhost:8080"
echo "   • Client: http://localhost:8081"
echo ""
echo "🧪 Test Commands:"
echo ""
echo "  # Create normal request"
echo "  curl http://localhost:8081/orders/create"
echo ""
echo "  # Create slow request (>500ms latency)"
echo "  curl http://localhost:8081/orders/slow-status"
echo ""
echo "  # Create error request (500 status)"
echo "  curl http://localhost:8081/orders/internal-error"
echo ""
echo "📊 View Logs:"
echo "   tail -f /tmp/central-collector.log"
echo "   tail -f /tmp/tracking-client-demo.log"
echo "   tail -f /tmp/nextjs-dashboard.log"
echo ""
echo "🛑 Stop Services:"
echo "   pkill -f 'gradle bootRun'"
echo "   pkill -f 'npm run dev'"
echo ""
echo "🔄 Restart Services:"
echo "   bash /workspaces/leap-monitoring-platform/start-all.sh"
echo ""
echo "📚 Documentation:"
echo "   • Setup Guide: /workspaces/leap-monitoring-platform/README_SETUP.md"
echo "   • Status Report: /workspaces/leap-monitoring-platform/SYSTEM_STATUS.md"
echo ""
